import Nav from "./auth/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	style: ["normal"],
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Component changed to jsx because TyoeScript is having tough time recognizing
 * server components, will throw error
 */

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`mx-4 md:mx-8 xl:mx-96 ${inter.variable} bg-slate-100`}
			>
				<Nav />
				{children}
			</body>
		</html>
	);
}
